startPort: 10001
healthCheckTimeout: 120
logLevel: info
models:
  gpt-oss-20b-UD-Q8_K_XL:
    cmd: >-
      "Z:\Python\AI Assistant\littlellm\llama\llama-server.exe" --model
      "C:\Users\npitt\Downloads\models\gpt-oss-20b-UD-Q8_K_XL.gguf" --port
      ${PORT} --host 127.0.0.1 --ctx-size 4096 --threads 4
    proxy: http://127.0.0.1:8080
    name: Gpt Oss 20b UD Q8_K_XL
    ttl: 300
