name: Validate NEEDFIXES.md

on:
  push:
    paths:
      - 'NEEDFIXES.md'
      - '.markdownlint.json'
  pull_request:
    paths:
      - 'NEEDFIXES.md'
      - '.markdownlint.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate NEEDFIXES.md
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install -g markdownlint-cli markdown-link-check
        
    - name: Run markdown linter
      run: markdownlint NEEDFIXES.md --config .markdownlint.json
      
    - name: Check links
      run: markdown-link-check NEEDFIXES.md
      
    - name: Verify document structure
      run: |
        echo "Checking for required sections..."
        grep -q "## 0️⃣ Executive Summary" NEEDFIXES.md && echo "✅ Executive Summary found" || (echo "❌ Executive Summary missing" && exit 1)
        grep -q "## Next Steps Checklist for Maintainers" NEEDFIXES.md && echo "✅ Next Steps found" || (echo "❌ Next Steps missing" && exit 1)
        grep -q "Expected Impact Summary" NEEDFIXES.md && echo "✅ Expected Impact Summary found" || (echo "❌ Expected Impact Summary missing" && exit 1)
        echo "🎉 All required sections found!"
        
    - name: Success message
      run: |
        echo "🎉 NEEDFIXES.md validation completed successfully!"
        echo "📊 Document is ready for team review."
